version: '3.6'

services:
  app_under_test:
    image: govukpay/${IMAGE}:${TAG}
    env_file: ${WORKSPACE}/test/cypress/test.env
    environment:
      PORT: 3000
      CONNECTOR_URL: http://stub:8000
      CONNECTOR_HOST: http://stub:8000
      CARDID_HOST: http://stub:8000
      DIRECT_DEBIT_CONNECTOR_URL: http://stub:8000
      PUBLIC_AUTH_BASE: http://stub:8000
      PUBLIC_AUTH_URL: http://stub:8000/v1/frontend/auth
      ADMINUSERS_URL: http://stub:8000
      PRODUCTS_URL: http://stub:8000
      LEDGER_URL: http://stub:8000
      WEBHOOKS_URL: http://stub:8000
      ZENDESK_URL: http://stub:8000
      WORLDPAY_3DS_FLEX_DDC_TEST_URL: http://stub:8000/shopper/3ds/ddc.html
      STRIPE_KYC_ADDITIONAL_DATA_DUE_DATE: "1 November 2021"
      STRIPE_HOST: stub
      STRIPE_PORT: 8000
      STRIPE_PROTOCOL: http
    logging:
      driver: "json-file"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app_under_test:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  cypress:
    image: cypress/included:${CYPRESS_VERSION:-"9.5.0"}
    environment:
      NO_COLOR: 1
      CYPRESS_BASE_URL: http://app_under_test:3000
      CYPRESS_MOUNTEBANK_URL: http://stub:2525
      CYPRESS_MOUNTEBANK_IMPOSTERS_PORT: 8000
    volumes:
      - ${WORKSPACE}/test/cypress:/app/test/cypress
      - ${WORKSPACE}/cypress.json:/app/cypress.json
      - ${WORKSPACE}/node_modules:/app/node_modules
      - ${WORKSPACE}/test/fixtures:/app/test/fixtures
      - ${WORKSPACE}/app/models:/app/app/models
    logging:
      driver: "json-file"
    depends_on:
      - stub
      - app_under_test
    working_dir: /app

  stub:
    image: govukpay/mountebank:2.1.2
    logging:
      driver: "json-file"
    ports:
      - 8000
      - 2525
